# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(help_text='Course', max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, help_text='Course Name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for each and every Lecture', primary_key=True, serialize=False)),
                ('lecture_date_time', models.DateTimeField(help_text='Date of the Lecture')),
                ('lecture_image', models.ImageField(help_text='Image of Lecture', upload_to='')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Course')),
            ],
            options={
                'ordering': ['lecture_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(help_text='Enter Roll Number', max_length=25, primary_key=True, serialize=False)),
                ('student_image', models.ImageField(help_text='Student Image', upload_to='', verbose_name=models.CharField(help_text='Enter Roll Number', max_length=25, primary_key=True, serialize=False))),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Lecture')),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter Second Name', max_length=100)),
                ('course_id', models.ManyToManyField(to='image.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Teacher_name',
            field=models.ManyToManyField(to='image.Teacher'),
        ),
    ]
