# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course_id',
        ),
    ]
