# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_auto_20171117_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lecture_id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='student_roll_no',
            field=models.CharField(blank=True, help_text='After a while', max_length=25),
        ),
    ]
