# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20171117_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Enter First Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(help_text='Enter Second Name', max_length=100, null=True),
        ),
    ]
