# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0010_auto_20171117_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(help_text='Student Image', upload_to='StudentImages/<django.db.models.fields.CharField>/', verbose_name=models.CharField(help_text='Enter Roll Number', max_length=25, primary_key=True, serialize=False)),
        ),
    ]
