# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20171117_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course_id',
            field=models.ManyToManyField(blank=True, to='image.Course'),
        ),
    ]
