# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_auto_20171121_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='student_roll_no',
            field=models.ManyToManyField(blank=True, to='image.Student'),
        ),
    ]
