# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0016_auto_20171121_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['-lecture_date_time']},
        ),
    ]
