# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0021_auto_20171125_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='student_roll_no',
            field=models.ManyToManyField(blank=True, to='image.Student'),
        ),
    ]
