# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0023_auto_20171125_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_image',
            field=models.ImageField(help_text='Image of Lecture', upload_to='media/lectures/%Y/%m/%d/'),
        ),
    ]
